### ISSUE TITLE
Genera el código al final del constructor

### ISSUE THREAD

**Issue by lmagarin** [albertommartinez/Programacion1819#2]
https://github.com/albertommartinez/Programacion1819/blob/b94b87538d2c14c14a93861a28840533f10750fd/Articulo.java#L16

**Comment by albertommartinez** [comment]
hecho

**Comment by lmagarin** [comment]
¿Dónde?
😃

**Comment by albertommartinez** [comment]
Lee he dao sin querer al botón perdona, pero ese issue ya está arreglado
pero no subido

**Comment by albertommartinez** [comment]
hecho
