### ISSUE TITLE
Encapsulamiento.

### ISSUE THREAD

**Issue by lmagarin** [albertommartinez/Programacion1819#3]
https://github.com/albertommartinez/Programacion1819/blob/b94b87538d2c14c14a93861a28840533f10750fd/Almacen.java#L11

Encapsulamiento.
En el diseño de los objetos el encapsulamiento es primordial. 
En la medida de lo posible, tanto estado como comportamiento han de encapsularse.

**Comment by albertommartinez** [comment]
hecho
