### ISSUE TITLE
Sobra la comunicación con el usuario

### ISSUE THREAD

**Issue by lmagarin** [albertommartinez/Programacion1819#4]
https://github.com/albertommartinez/Programacion1819/blob/b94b87538d2c14c14a93861a28840533f10750fd/Almacen.java#L23
Capa de presentación??
Sólo en la capa de presentación puede haber comunicación con el usuario. Aquí ni println ni Teclado
https://es.wikipedia.org/wiki/Programaci%C3%B3n_por_capas

**Comment by albertommartinez** [comment]
hecho
